title: Nick's data journey
name: Nick Stamboglis, my Journey in Data
description: Sharing my experiences on data science and management 
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
